= Minimal Debian (Wheezy) Docker Image

== Introduction
This is a basic debian (wheezy) docker image with cUrl and wget installed

== Image Tag/Name
The image tag/name will be
....
classicdriver/base
....

== How to build this image
. Clone the Git repository
+
....
git clone http://<git.host>/docker-base.git
....
. Browse to the parent folder of the cloned repository
+
....
cd <parent-folder>
....
. Build the docker image with the command
+
....
docker build --rm=true --tag=classicdriver/base docker-base/.
....
. List all the available images
+
....
docker images
....
There should be an image named *classicdriver/base*
. Test the docker image by running the command
+
....
docker run -it --rm=true classicdriver/base /bin/bash
....
. The console will be attached to the running container
. Run the following command
+
....
root@<DOCKER-CONTAINER-ID>:/# curl
....
.. The expected output should be
+
....
curl: try 'curl --help' or 'curl --manual' for more information
....
. Exit the container
